config/routes.rb
Rails.application.routes.draw do
  resources :early_signups

  root 'pages#home'

end

app/models/early_signup.rb
class EarlySignup < ActiveRecord::Base
    before_save {self.email = email.downcase}
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
    validates :email, presence: true, length: {maximum: 105}, 
               uniqueness: {case_sensitive: false},
               format: {with: VALID_EMAIL_REGEX}
               
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/early_signups_controller.rb
class EarlySignupsController < ApplicationController
  before_action :set_early_signup, only: [:show, :edit, :update, :destroy]

  # GET /early_signups
  # GET /early_signups.json
  def index
    @early_signups = EarlySignup.all
  end

  # GET /early_signups/1
  # GET /early_signups/1.json
  def show
  end

  # GET /early_signups/new
  def new
    @early_signup = EarlySignup.new
  end

  # GET /early_signups/1/edit
  def edit
  end

  # POST /early_signups
  # POST /early_signups.json
  def create
    @early_signup = EarlySignup.new(early_signup_params)
    
    if @early_signup.save
      flash[:success] = "You are signed up to get updates! Check out our Design Wizard."
    else
      flash[:danger] = @early_signup.errors.full_messages.join(", ").html_safe
    end
    redirect_to root_path
  end
    """
    respond_to do |format|
      if @early_signup.save
        format.html { redirect_to @early_signup, notice: 'Early signup was successfully created.' }
        format.json { render :show, status: :created, location: @early_signup }
      else
        format.html { render :new }
        format.json { render json: @early_signup.errors, status: :unprocessable_entity }
      end
    end
    """
  
  # PATCH/PUT /early_signups/1
  # PATCH/PUT /early_signups/1.json
  def update
    respond_to do |format|
      if @early_signup.update(early_signup_params)
        format.html { redirect_to @early_signup, notice: 'Early signup was successfully updated.' }
        format.json { render :show, status: :ok, location: @early_signup }
      else
        format.html { render :edit }
        format.json { render json: @early_signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /early_signups/1
  # DELETE /early_signups/1.json
  def destroy
    @early_signup.destroy
    respond_to do |format|
      format.html { redirect_to early_signups_url, notice: 'Early signup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_early_signup
      @early_signup = EarlySignup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def early_signup_params
      params.require(:early_signup).permit(:email, :signed_up)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        #redirect_to articles_path if logged_in?
        @newEarlySignUp = EarlySignup.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/early_signups_helper.rb
module EarlySignupsHelper
end

app/views/early_signups/_form.html.erb
<%= render 'shared/errors', obj: @early_signup %>

<%= form_for(@early_signup) do |f| %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :signed_up %><br>
    <%= f.check_box :signed_up %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/early_signups/edit.html.erb
<h1>Editing Early Signup</h1>

<%= render 'form' %>

<%= link_to 'Show', @early_signup %> |
<%= link_to 'Back', early_signups_path %>

app/views/early_signups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Early Signups</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Signed up</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @early_signups.each do |early_signup| %>
      <tr>
        <td><%= early_signup.email %></td>
        <td><%= early_signup.signed_up %></td>
        <td><%= link_to 'Show', early_signup %></td>
        <td><%= link_to 'Edit', edit_early_signup_path(early_signup) %></td>
        <td><%= link_to 'Destroy', early_signup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Early signup', new_early_signup_path %>

app/views/early_signups/new.html.erb
<h1>New Early Signup</h1>

<%= render 'form' %>

<%= link_to 'Back', early_signups_path %>

app/views/early_signups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @early_signup.email %>
</p>

<p>
  <strong>Signed up:</strong>
  <%= @early_signup.signed_up %>
</p>

<%= link_to 'Edit', edit_early_signup_path(@early_signup) %> |
<%= link_to 'Back', early_signups_path %>

app/views/layouts/_footer.html.erb
<div class="panel-footer">
    Copyright &copy; Not--You
    <!--
    <ul>
        <li><# %= link_to "About", about_path %></li>
    </ul>
    -->
</div>

app/views/layouts/_messages.html.erb
<div class="container flashMessage">
  <div class="row center">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>  
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="/" class="navbar-brand"><img alt="brand" src=<%= image_url("ASO_logo_1x.png") %> /></a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#home">Home</a></li>
                <li><a href="#about">About</a></li>
            </ul>
            <button type="button" class="btn btn-default navbar-btn navbar-right">Try our Design Wizard</button>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Aso, Not Clothing</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  
  <body data-spy="scroll" data-target=".navbar-collapse">
    
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    
    <%= yield %>  
    
    <%= render 'layouts/footer' %>
    
    <%= debug(params) if Rails.env.development? %>
    
    <script>
			$(".contentContainer").css("minHeight", $(window).height());
			console.log($(window).height());
		</script>
    
  </body>

</html>

app/views/pages/home.html.erb
<div class="container contentContainer" id="home">
    <div class="row">
        <div class="col-md-6 col-md-offset-3" id="topRow">
            <h1 class="marginTop">The most efficient way to make Nigerian clothing.</h1>
            <p class="lead left marginTop">
                Eliminate all the inefficiencies that come with making traditional Nigerian clothing. Use our Online Design Wizard to select fabric and design clothing, and we'll deliver to your doorstep.
            </p>
					
            <p class="bold marginTop">
                Interested? Sign up to know when we launch.
            </p>
            
            <%= form_for @newEarlySignUp, :url => early_signups_path, :html => {:method => :post} do |f| %>
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    <%= f.email_field :email, class:"form-control", placeholder:"Your email" %>
                </div>
                <%= f.hidden_field :signed_up, {value: :false} %>
                <%= f.submit("Submit", class:'btn btn-primary btn-lg smallMarginTop') %>
            <% end %>
        </div>
    </div>
</div>
		
<div class="container contentContainer" id="about">
    <div class="row center">
        <h1 class="center title">Quality guaranteed.</h1>
        <p class="lead">Go from inspiration and ideas to beautiful clothing from the comfort of your home or office.</p>
    </div>
    <div class="row">
        <div class="col-md-4 marginTop center">
            <h3 class="center">Design</h3>
            <img src=<%= image_url("dummy_171x180.svg") %> alt="..." class="marginTop" />
            <p class="marginTop">
                Our interactive design wizard allows you to select from an extensive pool of designs and pair with fabric of your choice. Design individual pieces or complete outfits with ease.
            </p>
        </div>
        <div class="col-md-4 marginTop center">
            <h3 class="center">Accuracy</h3>
            <img src=<%= image_url("dummy_171x180.svg") %> alt="..." class="marginTop" />
            <p class="marginTop">
                We have only one size: yours. Upload your measurements or choose from standard sizes to get your very best fit. Our expert tailors bring your ideas to life with bullseye precision.
            </p>
        </div>
        <div class="col-md-4 marginTop center">
            <h3 class="center">Speed</h3>
            <img src=<%= image_url("dummy_171x180.svg") %> alt="..." class="marginTop" />
            <p class="marginTop">
                Getting traditional clothing no longer has to take ages. Ordered clothing gets to your doorstep within days.
            </p>
        </div>
    </div>
    <div class="center marginTop">
        <button type="button" class="btn btn-default btn-lg">Try our Design Wizard</button>
    </div>
</div>

<style>
    $(".contentContainer").css("minHeight", $(window).height());
    console.log($(window).height())
</style>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row flashMessage">
        <div class="col-xs-6 col-xs-offset-3">
            <div class="panel panel-danger">
                <div class="panel-heading">
                   <h3 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prevented changes from being saved:
                    </h3>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li><%=  msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>